apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: customercli
  name: customercli
spec:
  ports:
  - name: "50058"
    port: 50058
    targetPort: 50051
  selector:
    io.kompose.service: customercli
