apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: productcli
  name: productcli
spec:
  ports:
  - name: "50060"
    port: 50060
    targetPort: 50051
  selector:
    io.kompose.service: productcli
