apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: promotioncli
  name: promotioncli
spec:
  ports:
  - name: "50052"
    port: 50052
    targetPort: 50051
  selector:
    io.kompose.service: promotioncli
