apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: usercli
  name: usercli
spec:
  ports:
  - name: "50054"
    port: 50054
    targetPort: 50051
  selector:
    io.kompose.service: usercli
