apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotemp-ingress
spec:
  rules:
    - host: gotempm.tst
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 443

