apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotemp-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: gotemp.tst
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microapi
                port:
                  number: 8080

