apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ./../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ./../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: web
    spec:
      containers:
        - image: bolbeck/gotemp_web
          imagePullPolicy: ""
          name: gtweb
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
