apiVersion: v1
data:
  DISABLE_AUDIT_RECORDS: "false"
  MICRO_BROKER: nats
  MICRO_BROKER_ADDRESS: natsUser:TestDB@home2@nats
  MICRO_SERVER_ADDRESS: :50051
  MICRO_STORE: redis
  MICRO_STORE_ADDRESS: redis://:TestDB@home2@redis:6379
  POSTGRES_CONNECT: postgresql://postgres:TestDB@home2@pgdb/postgres?application_name=promotionSrv
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: promotionsrv-promotion-docker-compose-env
  name: promotion-docker-compose-env
