apiVersion: v1
data:
  DISABLE_AUDIT_RECORDS: "false"
  MICRO_BROKER: nats
  MICRO_BROKER_ADDRESS: natsUser:TestDB@home2@nats
  MICRO_SERVER_ADDRESS: :50053
  POSTGRES_CONNECT: postgresql://postgres:TestDB@home2@pgdb/appuser?application_name=userSrv
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: usersrv-user-docker-compose-env
  name: user-docker-compose-env
